from logging import DEBUG, INFO, WARNING, ERROR

data_path = "/home/pegro/wohnen/data/main"

loglevel = DEBUG
logfile = f"{data_path}/scrape.log"

name_from = "Wohnungsschnüffler"
email_from = "wo-schnueffi@example.com"

smtp_server = "localhost"

## Set searches
## This only has an effect when run with --scrape
query_parameters = {
    'area_min': 42,
    'rooms_min': 2,
    'rooms_max': 5,
    'rent_base_max': 600,
    'rent_total_max': 770,
    'wbs': 0
}

filter = {
    'allow': {
    },
    'block' : {
        'title' : [
            'untermiete',
            'zwischenmiete',
            'zwischemiete',
            'zwischenvermiet',
            'suche wohnung',
            'suche 1',
            'suche 2',
            'suche 3',
            'suche eine ',
            'suche ein zimmer',
            'suche mietwohnung',
            'zum teilen',
            'nur tauch',
            'tausch',
            'tauch wohnung',
            'tauchwohnung',
            'zimmer gegen',
            'swap',
            'sublet',
            'subrent',
            'auf zeit',
            'kurzzeit',
            ' befristet',
            'temporary',
            'für monat ',
            ' tage ',
            ' week',
            ' month',
            ' wochen',
            ' monate',
            '1 monat',
            ' wg ',
            ' wg-',
            '-wg',
            'wg zimmer',
            'wg-zimmer',
            'er wg',
            'er-wg',
            'wohngemeinschaft',
            'mitbewohner',
            'shared apartment',
            'shared room',
            '*wbs*',
            'mit wbs',
            'wbs mit',
            '+ wbs',
            '!wbs',
            'wbs-wohn',
            'wbs-berechtigte',
            'wbs-pflichtig',
            'bedingung wbs',
            'wbs wohnung',
            'ferienwohnung',
            'ferien wohnung',
            'familie',
            'monteur',
            'montage ',
            'montagewohnung',
            'studentenwohnheim',
            'studenten-appartement',
            'studenten wohnanlage',
            'nur für studenten',
            'students only',
            'anfragestop',
            'suche stellplatz',
            'fensterputzer',
            'münchen',
            'eberswalde',
            'ukraine',
            'belohnung',
            'prämie',
            'ohne anmeldung',
            ' möblierte ',
            'voll möbliert',
        ],
        'kiez': [
            'steglitz',
            'zehlendorf',
            'wannsee',
            'mariendorf',
            'marienfelde',
            'buckow',
            'wilhelmsruh',
            'dahlem',
            'spandau',
            'wittenau',
            'tegel',
            'grunewald',
            'lichterfelde',
            'lankwitz',
            'lichtenrade',
            'gropiusstadt',
            'rudow',
            'adlershof',
            'köpenick',
            'grünau',
            'biesdorf',
            'mahlsdorf',
            'friedrichsfelde',
            'kaulsdorf',
            'hellersdorf',
            'marzahn',
            'hohenschönhausen',
            'heinersdorf',
            'buch',
            'märkisches viertel',
            'rosenthal',
            'blankenburg',
            'hermsdorf',
            'falkenhagener feld',
            'staaken',
            'friedenau',
            'westend',
            'lübars',
            'haselhorst',
            'siemensstadt',
            'waidmannslust',
            'altglienicke'
        ],
        'Beschreibung': [ # ebay kleinanzeigen field
            'das zweite foto',
            'das zweite bild',
            'vielzahl an nachrichten',
            'vielzahl von nachrichten',
            'nur auf instagram',
            'untervermieten',
            'untermiet',
            'zwischenmiete',
            'zwischen miete',
            'on vacation for',
            'flat share',
            'auf zeit',
            'short-term',
            'temporary',
            'für die zeit',
            'from now until',
            ' tage ',
            'monatsweise',
            'nur tausch',
            'ich tausche',
            'zum tausch',
            'im tausch',
            'tauschen',
            'wohnungstausch',
            'tauschwohnung',
            'swap only',
            'ich suche eine ',
            'wir suchen eine ',
            'belohnung',
            'lundberg',
            'lofgren',
            'monteur',
            'büroplatz',
            'pendler',
            'vermietende',
            'ohne anmeldung',
            'keine anmeldung',
            'wg zimmer',
            'lorem ipsum'
        ]
    }
}
